steps:
  - checkout: self
    persistCredentials: true
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: '$(MAVEN_CACHE_FOLDER)'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '$(JDK_VERSION)'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: Docker@2
    inputs:
      command: buildAndPush
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      repository: $(IMAGE_NAME)
      containerRegistry: $(REGISTRY_CONNECTION_NAME)
      tags: |
        $(Build.BuildNumber)
        latest
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        git config --global user.email "azure.devops.pipelines@$(Build.DefinitionName)"
        git config --global user.name "Azure DevOps Pipelines"
        git tag -a $(Build.BuildNumber) -m "Container build from $(Build.SourceBranchName)"
        git push --tags
